Increase the async timeout
Before, it wasn't possible to run the file checks on large files of around
1 GB or more. They hit the old 10 second timeout and the Lambda would fail
with the error:

```
Future timed out after [10 seconds]: java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException: Future timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.result(package.scala:124)
	at uk.gov.nationalarchives.downloadfiles.Lambda.process(Lambda.scala:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

Set a much longer timeout (2.5 minutes) to make it possible to download
larger files.

This needs to be shorter than the Lambda's own timeout, which is currently
3 minutes:
https://github.com/nationalarchives/tdr-terraform-modules/blob/157cc60c0f102427573a368e78d5e6d6c7e752ce/lambda/download_files.tf#L8

We can tune this timeout further if necessary.